# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    build:
        context: .
    image: wordpress_with_plugin
    ports:
      - '8080:8080'
        # - '443:8443'
    volumes:
     - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_EXTRA_WP_CONFIG_CONTENT=define('PROMETHEUS_KEY','d711d81a-18d2-4a04-b36d-2981200ebd78');define('PROMETHEUS_METRICS_FOR_WP_DISABLE_CACHE', true);
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
