global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: my-application
  honor_labels: true
  static_configs:
    - targets: ['go-application:5000','python-application:5000','dotnet-application:5000','nodejs-application:5000']
- job_name: wordpress-application
  honor_labels: true
  static_configs:
    - targets: ['wordpress-application:8080']
  metrics_path: /wp-json/metrics
  params:
    prometheus: ['d711d81a-18d2-4a04-b36d-2981200ebd78']
    all: ['yes']
      #    users: ['yes']
      #    posts: ['yes']
      #    pages: ['yes']
      #    autoload: ['yes']
      #    transient: ['yes']
      #    user_sessions: ['yes']
      #    posts_without_content: ['yes']
      #    posts_without_title: ['yes']
      #    db_size: ['yes']
      #    pending_updates: ['yes']
