FROM golang:1.22-alpine as builder

# installing git
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /go/src/app

COPY go.mod go.sum .

RUN go mod download

COPY . .

RUN go build -o myapp

FROM alpine

RUN apk update && apk upgrade && \
    apk add --no-cache openssh curl ca-certificates

WORKDIR /go/src/app
COPY --from=builder /go/src/app/myapp /go/src/app/myapp

EXPOSE 5000

CMD ["./myapp"]
